spring:
  application:
    name: usuarios-service
  
  datasource:
    url: jdbc:postgresql://localhost:5432/arrendamiento_db
    username: arrendamiento_user
    password: arrendamiento_pass
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8080

logging:
  level:
    com.arrendamiento: DEBUG
    org.springframework.web: INFO

