server:
  port: 8080

spring:
  application:
    name: administracion-service
  
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/arrendamiento_db}
    username: ${SPRING_DATASOURCE_USERNAME:arrendamiento_user}
    password: ${SPRING_DATASOURCE_PASSWORD:arrendamiento_pass}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: ${JWT_SECRET:myVerySecretKeyForArrendamientoAdministracion2023}
  expiration: ${JWT_EXPIRATION:86400}

logging:
  level:
    com.arrendamiento.administracion: DEBUG
    org.springframework.security: DEBUG
